// Program Argument: 
// <PathTo dataset>/sequences/00/image_0/ <PathTo dataset>/sequences/00/image_1/ <PathTo dataset>/sequences/00/calib.txt <Number of Frames you want to compute> Xilinx xilinx_u50_gen3x16_xdma_5_202210_1

/**
 * folder directory structure:
 * 
 * ${ProjectFolder}
 *  |- ${HostFolder}
 *  |   |- src
 *  |   |   |- C_FeatureExtraction  
 *  |   |   |- C_FeatureTracking
 *  |   |   |- C_MotionEstimation
 *  |   |   |- C_StereoMatching
 *  |   |   |- K_FeatureExtraction
 *  |   |   |- K_FeatureTracking
 *  |   |   |- K_MotionEstimation
 *  |   \   \- K_StereoMatching
 *  |      
 *  |- Output  
 *  |   |- C_FeatureExtraction  
 *  |   |- C_FeatureTracking
 *  |   |- C_MotionEstimation
 *  |   |- C_StereoMatching
 *  |   |- K_FeatureExtraction
 *  |   |- K_FeatureTracking
 *  |   |- K_MotionEstimation
 *  |   \- K_StereoMatching
 *  |- dataset
 *  |   |- poses
 *  \   \- sequences
 * 
 */


//================================1.  Include Section================================
/**
 * Please fill the include path of your main function in pure C code
 * 
 * folder directory structure:
 * 
 * ---${Host_Folder}
 *  |- src
 *  |   |- C_FeatureExtraction  
 *  |   |- C_FeatureTracking
 *  |   |- C_MotionEstimation
 *  |   |- C_StereoMatching
 *  |   |- K_FeatureExtraction
 *  |   |- K_FeatureTracking
 *  |   |- K_MotionEstimation
 *  |   |- K_StereoMatching
 * 
 * 
 */
#include "C_StereoMatching/Methods_S.h"			//stereo_2_depth(unsigned char* image_left_test_data, unsigned char* image_right_test_data, unsigned char* k_left_test_data, unsigned char* t_left_test_data, unsigned char* t_right_test_data, bool matcher, bool rgb, bool rectified, unsigned char* depth_map);
#include "C_FeatureExtraction/Methods.h"		//extract_features(unsigned char* image_data, unsigned char* mask_data, float* kp_xy, unsigned char* des_data);
#include "C_FeatureTracking/FeatureMatching.h"	//match_feature(uchar *des0, uchar *des1, FLOAT dist_threshold, int32 *match);
#include "C_MotionEstimation/EstimateMotion.h"	//EstimateMotion::estimate(Matrix &match, Matrix &kp0, Matrix &kp1, Matrix &k, Matrix &depth, Matrix &rmat, Matrix &tvec);
#include "C_MotionEstimation/Matrix.h"
//================================Include Section END================================


//=================================2.  Macro Section=================================
/**
 * 6 compile modes:
 * `_PURE_C_`                   // Run all function in pure C code
 * `_ONLY_K_StereoMatching_`    // Run all function in pure C code excluding `StereoMatching` kernel
 * `_ONLY_K_FeatureExtraction_` // Run all function in pure C code excluding `FeatureExtraction` kernel
 * `_ONLY_K_FeatureTracking_`   // Run all function in pure C code excluding `FeatureTracking` kernel
 * `_ONLY_K_MotionEstimation_`  // Run all function in pure C code excluding `MotionEstimation` kernel
 * `_ALL_KERNELS_`              // Run all function in HLS code
 *
 * 2 message modes
 * `_INFO_`                     // Print the program progress on terminal
 * `_PRINT_`                    // Write the output of function to .txt file 
 *
 * The default mode is `_ALL_KERNELS_` + `_INFO_` + `_PRINT_`
 */

#define _ONLY_K_FeatureExtraction_
//#define _PURE_C
#define _INFO_
#define _PRINT_

//=================================Macro Section END=================================


//===============================3.  Parameter Section===============================
/**
 * Please fill the name of your main function in kernel without "()"
 * Also the path of your output folder 
 * 
 * output folder directory structure:
 * 
 * --- Output
 *  |- C_FeatureExtraction  
 *  |       // Contains Des0, Des1 ,KP0, KP1 generated by pure C code
 *  |- C_FeatureTracking
 *  |       // Contains Matches generated by pure C code  
 *  |- C_MotionEstimation
 *  |       // Contains rmat, tvec generated by pure C code
 *  |- C_StereoMatching
 *  |       // Contains Depth generated by pure C code
 *  |- K_FeatureExtraction
 *  |       // Contains Des0, Des1 ,KP0, KP1 generated by HLS code
 *  |- K_FeatureTracking
 *  |       // Contains Matches generated by HLS code
 *  |- K_MotionEstimation
 *  |       // Contains rmat, tvec generated by HLS code
 *  |- K_StereoMatching
 *  |       // Contains Depth generated by HLS code
 * 
 * 
 */
#define Filter 1

#define K_StereoMatching_NAME "stereo_2_depth"
#define K_FeatureExtraction_NAME "extract_features"
#define K_FeatureTracking_NAME "K_FeatureTracking"
#define K_MotionEstimation_NAME "K_MotionEstimation"
#define OUTPUT_FOLDER_PATH "/home/hls02/r11922045/orb_workspace/output/"
//===============================Parameter Section END===============================
